// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CoinbaseAccountHoldsOptions struct {
	Before *string `json:"before"`
	After  *string `json:"after"`
	Limit  *int    `json:"limit"`
}

type CoinbaseAccountLedgerOptions struct {
	StartDate *string `json:"startDate"`
	EndDate   *string `json:"endDate"`
	Before    *string `json:"before"`
	After     *string `json:"after"`
	ProfileID *string `json:"profileId"`
	Limit     *int    `json:"limit"`
}

type CoinbaseAccountTransferOptions struct {
	Before *string `json:"before"`
	After  *string `json:"after"`
	Limit  *int    `json:"limit"`
	Type   *string `json:"type"`
}

type CoinbaseAccountTransfersOptions struct {
	Before *string `json:"before"`
	After  *string `json:"after"`
	Limit  *int    `json:"limit"`
	Type   *string `json:"type"`
}

type CoinbaseConversionOptions struct {
	ProfileID *string `json:"profileId"`
}

type CoinbaseConversionsOptions struct {
	ProfileID *string `json:"profileId"`
	From      string  `json:"from"`
	To        string  `json:"to"`
	Amount    float64 `json:"amount"`
	Nonce     *string `json:"nonce"`
}
