// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CoinbaseAccountDepositOptions struct {
	ProfileID         *string `json:"profileId"`
	Amount            float64 `json:"amount"`
	CoinbaseAccountID string  `json:"coinbaseAccountId"`
	Currency          string  `json:"currency"`
}

type CoinbaseAccountHoldsOptions struct {
	Before *string `json:"before"`
	After  *string `json:"after"`
	Limit  *int    `json:"limit"`
}

type CoinbaseAccountLedgerOptions struct {
	StartDate *string `json:"startDate"`
	EndDate   *string `json:"endDate"`
	Before    *string `json:"before"`
	After     *string `json:"after"`
	ProfileID *string `json:"profileId"`
	Limit     *int    `json:"limit"`
}

type CoinbaseAccountTransferOptions struct {
	Before *string `json:"before"`
	After  *string `json:"after"`
	Limit  *int    `json:"limit"`
	Type   *string `json:"type"`
}

type CoinbaseAccountTransfersOptions struct {
	Before *string `json:"before"`
	After  *string `json:"after"`
	Limit  *int    `json:"limit"`
	Type   *string `json:"type"`
}

type CoinbaseAccountWithdrawalOptions struct {
	ProfileID         *string `json:"profileId"`
	Amount            float64 `json:"amount"`
	CoinbaseAccountID string  `json:"coinbaseAccountId"`
	Currency          string  `json:"currency"`
}

type CoinbaseCoinbaseAccountDepositOptions struct {
	ProfileID         *string  `json:"profileId"`
	Amount            *float64 `json:"amount"`
	CoinbaseAccountID *string  `json:"coinbaseAccountId"`
	Currency          *string  `json:"currency"`
}

type CoinbaseConversionOptions struct {
	ProfileID *string `json:"profileId"`
}

type CoinbaseConversionsOptions struct {
	ProfileID *string `json:"profileId"`
	From      string  `json:"from"`
	To        string  `json:"to"`
	Amount    float64 `json:"amount"`
	Nonce     *string `json:"nonce"`
}

type CoinbasePaymentMethodDepositOptions struct {
	ProfileID       *string `json:"profileId"`
	Amount          float64 `json:"amount"`
	PaymentMethodID string  `json:"paymentMethodId"`
	Currency        string  `json:"currency"`
}
