version: '3'
services:
  goimports:
    build:
      context: ./schema
      dockerfile: goimports.Dockerfile
  generate:
    build:
      context: ./schema
      dockerfile: generate.Dockerfile
    command: [ruby, /usr/src/schema/generate.rb]
    volumes:
      - ./protomodel:/usr/src/protomodel
      - ./schema/comment.rb:/usr/src/schema/comment.rb
      - ./schema/endpoint_state.rb:/usr/src/schema/endpoint_state.rb
      - ./schema/endpoint.rb:/usr/src/schema/endpoint.rb
      - ./schema/field.rb:/usr/src/schema/field.rb
      - ./schema/generate.rb:/usr/src/schema/generate.rb
      - ./schema/model:/usr/src/schema/model
      - ./schema/path_part.rb:/usr/src/schema/path_part.rb
      - ./schema/protomodel.rb:/usr/src/schema/protomodel.rb
      - ./schema/query_param.rb:/usr/src/schema/query_param.rb
      - ./schema/scheme.rb:/usr/src/schema/scheme.rb
    depends_on:
      - goimports
  test_generate:
    build:
      context: ./schema
      dockerfile: generate.Dockerfile
    command: [ruby, /usr/src/schema/test/test.rb]
    volumes:
      - ./protomodel:/usr/src/protomodel
      - ./schema/comment.rb:/usr/src/schema/comment.rb
      - ./schema/endpoint_state.rb:/usr/src/schema/endpoint_state.rb
      - ./schema/endpoint.rb:/usr/src/schema/endpoint.rb
      - ./schema/field.rb:/usr/src/schema/field.rb
      - ./schema/generate.rb:/usr/src/schema/generate.rb
      - ./schema/model:/usr/src/schema/model
      - ./schema/path_part.rb:/usr/src/schema/path_part.rb
      - ./schema/protomodel.rb:/usr/src/schema/protomodel.rb
      - ./schema/query_param.rb:/usr/src/schema/query_param.rb
      - ./schema/scheme.rb:/usr/src/schema/scheme.rb
      - ./schema/test:/usr/src/schema/test
    depends_on:
      - goimports
