version: '3'
services:
  goimports:
    build:
      context: ./meta
      dockerfile: goimports.Dockerfile
  generate:
    build:
      context: ./meta
      dockerfile: generate.Dockerfile
    command: [ruby, /usr/src/meta/generate.rb]
    volumes:
      - ./coinbase:/usr/src/coinbase
      - ./kraken:/usr/src/kraken
      - ./iex:/usr/src/iex
      - ./opensea:/usr/src/opensea
      - ./graph:/usr/src/graph
      - ./gqlgen.yml:/usr/src/gqlgen.yml
      - ./model:/usr/src/model
      - ./protomodel:/usr/src/protomodel
      - ./meta/comment.rb:/usr/src/meta/comment.rb
      - ./meta/endpoint_store.rb:/usr/src/meta/endpoint_store.rb
      - ./meta/endpoint.rb:/usr/src/meta/endpoint.rb
      - ./meta/field.rb:/usr/src/meta/field.rb
      - ./meta/generate.rb:/usr/src/meta/generate.rb
      - ./meta/graph_schema.rb:/usr/src/meta/graph_schema.rb
      - ./meta/schema:/usr/src/meta/schema
      - ./meta/model.rb:/usr/src/meta/model.rb
      - ./meta/path_part.rb:/usr/src/meta/path_part.rb
      - ./meta/protomodel.rb:/usr/src/meta/protomodel.rb
      - ./meta/query_param.rb:/usr/src/meta/query_param.rb
      - ./meta/scheme.rb:/usr/src/meta/scheme.rb
      - ./meta/sdk_endpoints.rb:/usr/src/meta/sdk_endpoints.rb
    depends_on:
      - goimports
  test_generate:
    build:
      context: ./meta
      dockerfile: generate.Dockerfile
    command: [ruby, /usr/src/meta/test/test.rb]
    volumes:
      - ./coinbase:/usr/src/coinbase
      - ./kraken:/usr/src/kraken
      - ./iex:/usr/src/iex
      - ./opensea:/usr/src/opensea
      - ./graph:/usr/src/graph
      - ./gqlgen.yml:/usr/src/gqlgen.yml
      - ./model:/usr/src/model
      - ./protomodel:/usr/src/protomodel
      - ./meta/comment.rb:/usr/src/meta/comment.rb
      - ./meta/endpoint_store.rb:/usr/src/meta/endpoint_store.rb
      - ./meta/endpoint.rb:/usr/src/meta/endpoint.rb
      - ./meta/field.rb:/usr/src/meta/field.rb
      - ./meta/generate.rb:/usr/src/meta/generate.rb
      - ./meta/graph_schema.rb:/usr/src/meta/graph_schema.rb
      - ./meta/schema:/usr/src/meta/schema
      - ./meta/model.rb:/usr/src/meta/model.rb
      - ./meta/path_part.rb:/usr/src/meta/path_part.rb
      - ./meta/protomodel.rb:/usr/src/meta/protomodel.rb
      - ./meta/query_param.rb:/usr/src/meta/query_param.rb
      - ./meta/scheme.rb:/usr/src/meta/scheme.rb
      - ./meta/test:/usr/src/meta/test
      - ./meta/sdk_endpoints.rb:/usr/src/meta/sdk_endpoints.rb
    depends_on:
      - goimports
